### ISSUE TITLE
have tried with big data?

### ISSUE THREAD

**Issue by ucasiggcas** [JimLiu96/DeosciRec#2]
hi,dear
I have a dataset with 100,000 users ,40,000 items and about 4000,000 interactions,
but got the error,
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/logs/xulm1/DeosciRec/utilitys.py", line 336, in create_adj_mat
    cross_adj_mat = band_cross_hop_laplacian(adj_mat, low_pass=low, high_stop=high)
  File "/data/logs/xulm1/DeosciRec/utilitys.py", line 308, in band_cross_hop_laplacian
    cross_adj = adj.dot(adj)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/scipy/sparse/base.py", line 359, in dot
    return self * other
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/scipy/sparse/base.py", line 480, in __mul__
    return self._mul_sparse_matrix(other)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/scipy/sparse/base.py", line 539, in _mul_sparse_matrix
    return self.tocsr()._mul_sparse_matrix(other)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 509, in _mul_sparse_matrix
    np.asarray(other.indices, dtype=idx_dtype))
RuntimeError: nnz of the result is too large
```
So how to deal with the problem ?

**Comment by ucasiggcas** [comment]
without pretraining weights.
Epoch 0 [1545.7s]: train==[0.06498=0.06462 + 0.00035]
这个速度实际应用还是有差距啊，user 7万，item 3万，点击不到300万，小数据集都需要这么久啊

**Comment by ucasiggcas** [comment]
上面的报错是数据量的问题，如果能优化就好了。

**Comment by JimLiu96** [comment]
Did you try with the argument --low ? set big values for low, e.g., 0.01, or even 0.1. Additionally, this framework is not designed for a large-scale recommendation. You can combine this algorithm with other recommendation frameworks, e.g, LightGCN (https://github.com/kuandeng/LightGCN).

**Comment by ucasiggcas** [comment]
the fact is the LightGCN could not be used in big data either

**Comment by JimLiu96** [comment]
Then you are seeking billion-scale industry RS frameworks, which are rather different from our framework.

**Comment by ucasiggcas** [comment]
我说的big data，其实百万 用户都不到。

**Comment by JimLiu96** [comment]
I am talking about the number of edges, which dominates the complexity of the model. Actually, if you are working on millions of nodes, our model will initialize all the embedding, which requires a rather large size of memory. A dataset with millions of users is a pretty large dataset for most models from academics.
